### ISSUE TITLE
BAIKAL + nginx. php-7.4 Problreme

### ISSUE THREAD

**Issue by kuerbis42** [DIY-Blub/faq#11]
Baikal

Off-Topic: Danke für Deine Arbeit.

**Beschreibe den Fehler**
Ich habe Deine (Stand 12/2021) Anleitung auf **https://www.cenz.at/raspberry#webinterface** abgearbeitet.
(und benötigte das nur bis BAIKAL, der Rest ist nicht meins).
Nach der grundlegenden Installation funktiniert nginx inkl. php, auch die BAIKAL-Einrichtung (Datenbank) und die Admin-Seiten (Dashboard) funktionieren.

**Nicht richtig funktionieren tut der eigentliche Cal-/CardDAV-Aufruf:  **server.tld/dav.php** 
Die "Startseite" dav.php "geht noch" (auch nicht richtig), aber wenn man dann die Kalender-/Adressdaten "abholen will", kommt die Fehlermeldung "404 Page nocht found"**

Ähnlich wurde dieses Problem bereits hier einmal beschrieben: https://github.com/sabre-io/Baikal/issues/587
(brachte aber auch keine richtige Lösung)

Unter anderem ist die Demo-Config **nginx** bei **https://sabre.io/baikal/install/** mit ein Problem, den bzgl. PHP 7.4 ist sie "fehlerhaft".

Grundlegende Unterschiede zwischen Deiner Anleitung und meiner Installation:
**php-7.4 anstatt php-7.3**
baikal 0.8.0 anstatt 0.6.0

**Fehlermeldung / Logs?**
Wie dem auch sei, ich habe es jetzt hinbekommen und vielleicht aktulalisierst Du Deine Seite ein wenig, sprich, Anpassung der nginx-php Konfiguration.

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;


        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html/baikal/html;
        client_max_body_size 20M;

        # Add index.php to the list if you are using PHP
        index index.php index.html index.htm index.nginx-debian.html;
        rewrite ^/.well-known/caldav /dav.php redirect;
        rewrite ^/.well-known/carddav /dav.php redirect;
        charset utf-8;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
  location ~ ^(.+\.php)(.*)$ {
    try_files $fastcgi_script_name =404;
    include        /etc/nginx/fastcgi_params;
    fastcgi_split_path_info  ^(.+\.php)(.*)$;
    fastcgi_pass   unix:/run/php/php7.4-fpm.sock;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    fastcgi_param  PATH_INFO        $fastcgi_path_info;
  }
        # pass PHP scripts to FastCGI server
        #
        #       location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
        #       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #      fastcgi_pass 127.0.0.1:9000;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
```
Wichtig ist dieser Abteilung (in Anlehnung an sabre.io) mit der Änderung bei fastcgi_pass 

 **root /var/www/html/baikal/html;**
 client\_max\_body\_size 20M;

 index index.php index.html index.htm index.nginx-debian.html;
**rewrite ^/.well-known/caldav /dav.php redirect;**
**rewrite ^/.well-known/carddav /dav.php redirect;**
charset utf-8;
location / {
    try\_files $uri $uri/ =404;
}
location \~ ^(.+\.php)(.*)\$ {
    try\_files $fastcgi\_script\_name =404;
    include        /etc/nginx/fastcgi\_params;
    fastcgi\_split\_path\_info  ^(.+\.php)(.*)\$;
    fastcgi\_pass   unix:/run/php/**php7.4-fpm.sock**;
    fastcgi\_param  SCRIPT_FILENAME  $document\_root$fastcgi\_script\_name;
    fastcgi\_param  PATH_INFO        $fastcgi\_path\_info;
  }

Ansonsten: Danke für die Anleitung.
Gruß Frank

**Comment by DIY-Blub** [comment]
Hallo Frank,
danke für deine Nachricht! Zuerst einmal möchte ich klar stellen, dass meine Anleitung nicht Stand 12/2021 ist, sondern Oktober 2019 mit kleinen Anpassungen im Juni 2020. Die damalige Baikal-Version (also im Oktober 2019) war eben 0.6.x.

Prinzipiell greift man auf Baikal mit  _domain_/dav.php/calendars/_username_/_calendarname_/ bzw. _domain_/dav.php/addressbooks/_username_/_calendarname_/ zu. Vielleicht deshalb die Probleme.

Danke für den Post mit deiner Lösung!
Schöne Grüße,
Christian

**Comment by kuerbis42** [comment]
> Prinzipiell greift man auf Baikal mit _domain_/dav.php/calendars/_username_/_calendarname_/ bzw. _domain_/dav.php/addressbooks/_username_/_calendarname_/ zu. Meiner Erfahrung nach funktioniert _domain_/dav.php nur bei wenige Programme (z.B. DAVx5). Vielleicht deshalb die Probleme.

Ja, das ist richtig, aber genau "ab da" fangen die Probleme eben an: "file not found - 404"
Beim Aufruf von _domain_/_dav.php_ wird man ja per .htaccess aufgefordert, Benutzernamen und Kennwort einzugeben.
Die "nachfolgenden" URLs liefern aber wegen falscher nginx-Konfig eine 404-Fehler-Seite.

Der Fehler ist ja direkt auf der baikal-Seite

Der Aufruf _domain_/_dav.php_ wird von **DAVDroid**, **TBSync/Sabre DAV** und **Outlook CalDav Synchronizer** als "initial" URL akzeptiert. 

Frohe Tage noch
Frank
