### ISSUE TITLE
Werte von ADC werden unplausibel

### ISSUE THREAD

**Issue by alternativeEP** [DIY-Blub/faq#12]
Hi, habe eine Bewässerung mit Pi 4, 4 Kanal Relais und kapazitiven Sensoren für Bodenfeuchte nach deiner Vorlage gebaut. Die Relais schalten dann jeweils ein magnetventil für die Wasserzuführung und die Wasserpumpe (12volt). Anlage läuft auf 12v Batterie, Strom fürs PI kommt über DC/DC Netzteil mit 3a auf 5 Volt. Nach ein paar Tagen sinkt der Wert von Sensor 2 später 1 prozentuell ab, obwohl die Feuchtigkeit eigentlich i.O. ist. Ladegerät (ctek mikrocontroller) ist angeschlossen. Folglich findet eine überwässerung statt. Gibt es einen Erfahrungswert evtl. eine widerstandsschaltung beim ADC zu verbauen, die Phantom Spannungen an messeingängen eliminiert? Habe bei auftreten des Fehlers teilweise im sensorkal.py dann über 40% bodenfeuchte anstatt 0% wenn ich den Sensor abziehe und die Datei aufrufe

**Comment by DIY-Blub** [comment]
Hallo,

> Nach ein paar Tagen sinkt der Wert von Sensor 2 später 1 prozentuell ab, obwohl die Feuchtigkeit eigentlich i.O. ist. Ladegerät (ctek mikrocontroller) ist angeschlossen. Folglich findet eine überwässerung statt. [...] Habe bei auftreten des Fehlers teilweise im sensorkal.py dann über 40% bodenfeuchte anstatt 0% wenn ich den Sensor abziehe und die Datei aufrufe

Sorry, das verstehe ich nicht und kann ich nicht nachvollziehen. Die Sensoren werden vom RasPi versorgt (richtig?), somit sollte eine konstante Energieversorgung vorhanden sein. Sollten die Sensoren über I2C eingebunden sein, dann benötigen die Sensoren dennoch eine eigene Stromversorgung, weil I2C die Versorgung nicht konstant schafft.
Ich vermute jetzt mal da hier das Problem liegen könnte.

Zu Batterie und den anderen Punkten kann ich leider nicht weiterhelfen. Vielleicht kannst du für den ctek mikrocontroller in einem Mikrokontroller-Forum nachfragen?

**Comment by alternativeEP** [comment]
Ja korrekt, die Sensoren werden über raspi versorgt (5v, da kapazitive Sensoren). Komischerweise resettet sich alles wenn ich den ADC abziehe und wieder anstecke.

**Comment by DIY-Blub** [comment]
Ohne klare Rückmeldungen und Erläuterungen kann ich dir leider nicht helfen.
