### ISSUE TITLE
Buchsenleiste D-Sub (Polzahl 25) 

### ISSUE THREAD

**Issue by vknapczik** [DIY-Blub/faq#2]
@DIY-Blub 
Sehr geehrter Christian Enzersdorfer.

Wir beschäftigen uns mit ihrem Bewässerungssystem am Rasperry Pi 4 für Jugendforscht. Wir konnten bis jetzt immer noch nicht nachvollziehen, warum sie die Buchsenleiste benutzen. Da wir ein geringes Budget haben, wollten wir sie fragen, ob die Buchsenleiste erforderlich ist oder ob wir sie weglassen können. 

Mit freundlichen Grüßen 

Vincent

**Comment by DIY-Blub** [comment]
Guten Tag Vincent,

Die Buchsenleiste wurde als trennbare Verbindungsstelle, zwecks einfacher Handhabung bei Änderungen / Ergänzungen / usw. gewählt. Diese ist jedoch für den Betrieb nicht erforderlich und kann bei Bedarf getrost weggelassen werden.

Vielen Dank für Ihre Nachricht! Es freut mich sehr zu hören, dass meine Projekte umgesetzt werden. :)

Schöne Grüße,

Christian
